### ISSUE TITLE
Updating to 4026 Breaks T_QueryInterface

### ISSUE THREAD

**Issue by JoshuaChupp** [fisothemes/TwinCAT-Dynamic-String-Kit#2] opened 2024-08-21 20:09 UTC
I updated to TwinCAT build 4026 from 4024 and now I get C0090: No definition found for base class 'T_QueryInterface' [twincat dynamic string kit, 1.0.1.1 (fisothemes)]. Is there something new with 4026 causing this?

**Comment by fisothemes** [comment] 2024-08-22 17:27
This is interesting...
I've yet to use TwinCAT 4026 because it requires a fresh build. This is gonna takes sometime as I need to set up a new dev environment in a VM from scratch.

**Comment by fisothemes** [comment] 2024-09-12 19:34
I finally found the time to have a proper look at the issue (thank you MS for shutting down my PC for an update while WMWare is running and breaking my VM). I'll see if I can report it to Beckhoff. To me, it looks like Beckhoff/Codesys changed the way things are brought into scope in the compiler. It's a simple fix, but I honesty wish they provided a proper changelog as this could break large number of internal tooling in many organisations. IMO 4026 is still in beta.

**Comment by JoshuaChupp** [comment] 2024-09-25 16:38
Thanks. Let me know what Beckhoff says please

**Comment by wilber245** [comment] 2024-10-28 12:37
Any Update On this?

**Comment by fisothemes** [comment] 2024-10-28 17:07
I just dropped them an email. Will see what they say. In the meantime, I'll remove the alias.

**Comment by fisothemes** [comment] 2024-11-14 00:20
Beckhoff responded, and they confirmed this issue originates from the Codesys compiler, so it seems there’s nothing they can do on their end to resolve it. Additionally, I've received confirmation that the 4026 build is not yet production-ready. If you’re considering deploying a project using 4026, I strongly recommend consulting Beckhoff for further guidance.

**Comment by fisothemes** [comment] 2024-11-14 01:01
Fixed in [Pre-Release 1.0.2.2](https://github.com/fisothemes/TwinCAT-Dynamic-String-Kit/releases/tag/1.0.2.2)

**Closed as completed by fisothemes** 2024-11-14 01:01 UTC

**Comment by wilber245** [comment] 2024-11-14 14:16
Thanks for the update and fix, 
Based off your recommendation we may delay switching as we know how updates go.
